# Generated by Django 3.2.14 on 2022-07-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_item_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sold',
            new_name='Sold',
        ),
    ]
